version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: meudb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
